### ISSUE TITLE
feat: replace home made contact form by Cris Form plugin

### ISSUE THREAD

**Issue by p19y** [lacapsule/V4#9]

**Comment by p19y** [comment]
Now with Crisp Form installed on the Crisp account and the contact.html.

![Screenshot_20230115_151548](https://user-images.githubusercontent.com/73939446/212545937-fcfa9c21-23b7-42e0-8d2b-7c3315e6afa1.png)


I think it's gorgeous and now anyone in the team can answerr to Internet people

**Comment by p19y** [comment]
Even though the Crisp Form plugin is the most elegant way in my opinion to let Internet people reach us, this issue is not a real one since it happened when I hosted the website on localhost...

**Comment by lacapsule** [comment]
Okay, that's good but we're going to keep our technology which takes 10 lines against 850 for Crisp. Thanks anyway ;)
